apiVersion: v1
kind: Secret
metadata:
  name: minepulse-secrets
  namespace: minepulse
type: Opaque
stringData:
  POSTGRES_USER: "minepulse_user"
  POSTGRES_PASSWORD: "CHANGE_THIS_POSTGRES_PASSWORD_FOR_PROD"
  DATABASE_URL: "postgresql+psycopg2://minepulse_user:CHANGE_THIS_POSTGRES_PASSWORD_FOR_PROD@postgres-service:5432/minepulse_db"
  JWT_SECRET_KEY: "CHANGE_THIS_STRONG_JWT_SECRET_KEY_MIN_32_BYTES"
